### ISSUE TITLE
Migrate Render Math plugin to new shared repository

### ISSUE THREAD

**Issue by justinmayer** [pelican-plugins/render-math#1]
Now that @moorepants has extracted the Render Math plugin commits from the monolithic repository and added other enhancements, let's migrate his work to this new repository as a starting point for future development.

**Comment by justinmayer** [comment]
@moorepants said:

> How do we get access to push a plugin to https://github.com/pelican-plugins?
>
> I've converted render_math to a standalone repo: https://github.com/moorepants/render_math and can transfer the repo.

Many thanks for your patience, Jason. I created this new repository and added you as a collaborator. I also added @JWKennington, who has done some [parallel work](https://github.com/JWKennington/pelican-render-math) and who has graciously agreed to join forces and collaborate together here in this unified repository.

@moorepants: To get things started, would you please push the commits from your repository to this new shared repository so we can build upon it? Thank you!

**Comment by moorepants** [comment]
Will do!

**Comment by moorepants** [comment]
I'm getting permission denied on push.

**Comment by moorepants** [comment]
It's in! Needed to accept invite.

**Comment by justinmayer** [comment]
@moorepants: Fantastic. Looking forward to collaborating on it together! ✨
