### ISSUE TITLE
process_rst_and_summaries throws exception 

### ISSUE THREAD

**Issue by dclong** [pelican-plugins/render-math#5]
I'm using the current Pelican master branch, so this plugin works for me. However, one of my sub blogs throws the below exception. I'm using markdown and jupyter/lab notebooks but not RST. Could that be the reason? 
![image](https://user-images.githubusercontent.com/824507/82835164-1394bb80-9e78-11ea-9e86-cb7b980d21d8.png)

**Comment by dclong** [comment]
I temporarily resolve the issue by setting the variable `process_summary` to False. However, it does sound like a bug to me.

**Comment by justinmayer** [comment]
Closing this issue. If someone can post a comment here with detailed steps regarding how to reproduce the problem, I would be happy to re-open the issue.
